namespace Services.Factory.Logic
{
    public enum LogicFactoryType
    {
        MovableInputControl,
        ShootInputControl,
        InventoryInputControl,
        Damageable,
        Damager,
        DelayedDamage,
        DestroyFeatureOnDie,
        GameSpawn,
        Inventory,
        SpawnOffScreenPosition,
        CameraCharacterMoveRestriction,
        CharacterMoveRestriction,
        LookAtPlayer,
        MoveFollowPlayer,
        MoveForward,
        Rotate,
        CameraInitializeSize,
        DestroyableTickableUnsubscribe,
        Destroyable,
        DestroyableFeatureOutOfLevelBounds,
        DamageablePhysicsInitialize,
        DamageOnCollision,
        DestroyOnCollision,
        InventorySpawn,
        DelayedDamageOnCollision
    }
}